### ISSUE TITLE
Member Page

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/AYKYA-Fest#14]
## Requirements to be fulfilled 
- [x] Hamburger with navbar
- [x] Cards with flex layout
    - [x] On hover should colourise and display name
- [x] Footer

**Comment by suneel87** [comment]
I have used 5 different responsive tools online to check the view for the members page(I will provide the links below) and all the devices in all the tools didn't show any signs of overlap, extra space, unnecessary scroll bars. I have also modified the CSS so that the text decreases in size for mobile view.
The tools:
1) Am I Responsive: http://ami.responsivedesign.is/#
2) isResponsive: http://www.isresponsive.com/ViewOnDevice
3) Responsive Design Testing: http://mattkersley.com/responsive/
4) Responsinator: http://www.responsinator.com/
5) Designmodo: https://designmodo.com/responsive-test/

Link to use in all these sites: http://localhost:5000/members
